export const SIGN_UP_FAIL = "SIGN_UP_FAIL"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_IN_FAIL = "SIGN_IN_FAIL"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL"
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS"
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL"

export const SIGN_OUT = "SIGN_OUT"

export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS"
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL"
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN"

export const CLEAR_MESSAGES = "CLEAR_MESSAGES"

export const SET_USER_DATA = "SET_USER_DATA"
