export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS"
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL"

export const GET_SINGLE_CONVERSATION_SUCCESS = "GET_SINGLE_CONVERSATION_SUCCESS"
export const GET_SINGLE_CONVERSATION_FAIL = "GET_SINGLE_CONVERSATION_FAIL"

export const GET_NEWEST_CONVERSATION_SUCCESS = "GET_NEWEST_CONVERSATION_SUCCESS"
export const GET_NEWEST_CONVERSATION_FAIL = "GET_NEWEST_CONVERSATION_FAIL" 

export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL"
export const EDIT_MESSAGE_FAIL = "EDIT_MESSAGE_FAIL"
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL"
export const SEEN_MESSAGE_FAIL = "SEEN_MESSAGE_FAIL"

export const CLEAR_CONVERSATION_SUCCESS = "CLEAR_CONVERSATION_SUCCESS"
export const CLEAR_CONVERSATION_FAIL = "CLEAR_CONVERSATION_FAIL"

export const CLOSE_CONVERSATION = "CLOSE_CONVERSATION"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

