export const GET_FRIENDS_SUCCESS = "GET_FRIENDS"
export const GET_FRIENDS_FAIL = "GET_FRIENDS_FAIL"

export const GET_NEW_FRIENDS_SUCCESS = "GET_NEW_FRIENDS_SUCCESS"
export const GET_NEW_FRIENDS_FAIL = "GET_NEW_FRIENDS_FAIL"

export const SEARCH_FRIENDS_SUCCESS = "SEARCH_FRIENDS_SUCCESS"
export const SEARCH_FRIENDS_FAIL = "SEARCH_FRIENDS_FAIL"
export const CLEAR_SEARCH_FRIENDS = "CLEAR_SEARCH_FRIENDS"

export const GET_FRIEND_REQUESTS_SUCCESS = "GET_FRIEND_REQUESTS_SUCCESS"
export const GET_FRIEND_REQUESTS_FAIL = "GET_FRIEND_REQUESTS_FAIL"

export const ACCEPT_FRIEND_REQUEST_SUCCES = "ACCEPT_FRIEND_REQUEST_SUCCES"
export const ACCEPT_FRIEND_REQUEST_FAIL = "ACCEPT_FRIEND_REQUEST_FAIL"

export const REJECT_FRIEND_REQUEST_SUCCES = "REJECT_FRIEND_REQUEST_SUCCES"
export const REJECT_FRIEND_REQUEST_FAIL = "REJECT_FRIEND_REQUEST_FAIL"

export const BLOCK_FRIEND_SUCCESS = "BLOCK_FRIEND_SUCCESS"
export const BLOCK_FRIEND_FAIL = "BLOCK_FRIEND_FAIL"
export const UNBLOCK_FRIEND_FAIL = "BLOCK_FRIEND_FAIL"

export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS"
export const REMOVE_FRIEND_FAIL = "REMOVE_FRIEND_FAIL"

export const SEND_FRIEND_REQUEST_FAIL = "SEND_FRIEND_REQUEST_FAIL"